version: '2.1'

services:
  postgres:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      PGPASSWORD: "airflow"
      PGUSER: "airflow"
      POSTGRES_PASSWORD: "airflow"
      POSTGRES_USER: "airflow"
      POSTGRES_DB: "airflow"

  webserver:
    image: mastak/airflow:${AIRFLOW_VERSION:-2.0.1}
    restart: always
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: airflow
    volumes:
      - ./examples:/usr/local/airflow/dags
      - ./airflow_multi_dagrun:/usr/local/airflow/plugins/airflow_multi_dagrun
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

  scheduler:
    image: mastak/airflow:${AIRFLOW_VERSION:-2.0.1}
    restart: always
    depends_on:
      - postgres
      - webserver
    volumes:
      - ./examples:/usr/local/airflow/dags
      - ./airflow_multi_dagrun:/usr/local/airflow/plugins/airflow_multi_dagrun
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: airflow
    command: scheduler
